#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx mrm lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
npx lint-staged
